### ISSUE TITLE
Cannot push, I'm not an allowed user

### ISSUE THREAD

**Issue by flexo735** [Incognito23/Team2#1]
I tried to push my code earlier today (2 pm Tuesday) after finding out it didn't get pushed properly yesterday (1:30 Monday). I seem to be unable to push at all though, it says I am not an allowed contributor for this project. If you guys have any advice let me know.

**Comment by azkevin** [comment]
You should be an allowed user since it says you commited 6 days ago
Try re importing the project on eclipse and try pushing your java file again, or maybe you have to pull our stuff before you can push
